listen_port: "8080"

log_path: ""

redis_password: "root"
redis_is_cluster: false
redis_addr: "localhost:6379"

mysql_user: "root"
mysql_pwd: "root"
mysql_host: "localhost"
mysql_port: "3306"
mysql_db: "demo"
